In [40]:
import pandas as pd
import numpy as np
import UpdateME 
from UpdateME import cellfinder_output_path

In [51]:
mouse_id = 'test_005'

In [63]:
# Path to cellfinder_output points.npy file
cells_path = cellfinder_output_path + 'points/points.npy'
cells_path
points = np.load(cells_path)
print(points[15000])
print(points[25000])
print(points[35000])
print(points[45000])
print(points[55000])
print(points[65000])
print(points[75000])
print(points[85000])
print(points[95000])


[7750.  300. 7550.]
[8400.  450. 4500.]
[8900. 1000. 4050.]
[4750. 4900. 1900.]
[9450. 6050. 2150.]
[8550. 6700. 1700.]
[7650. 7300. 2550.]
[4600. 7150. 8250.]
[4500. 7450. 7550.]


### if you want to visualize data from a different mouse
#### update the cellfinder_output_path and mouse_id variables in the variables.py file in this repository

In [52]:
# import cellfinder inital data
gfp_df = pd.read_csv(cellfinder_output_path + 'analysis/' + 'gfp_summary.csv')
summary_df_0 = pd.read_csv(cellfinder_output_path + 'analysis/' + 'summary.csv')
tdTomato_df = pd.read_csv(cellfinder_output_path + 'analysis/' + 'tdTomato_summary.csv')

# import analyized data
labled_cells_df = pd.read_csv(cellfinder_output_path + mouse_id +'_Completed_analysis/' + mouse_id + '_labled_cells.csv')
summary_df = pd.read_csv(cellfinder_output_path + mouse_id + '_Completed_analysis/'+ mouse_id + '_summary_df.csv')

# Compare GFP to tdTomato labled cells
#### This was organized using the brain regions containing the most gfp cells in row 1 

In [53]:
print('You are currently looking at the following cellfinder output folder, and evaluating the following mouse_id')
print('')
print(cellfinder_output_path)

print('')
print(mouse_id)

You are currently looking at the following cellfinder output folder, and evaluating the following mouse_id

/Users/grant/Desktop/cellfinder_brainrender_output/cellfinder_output/

test_005


In [54]:
gfp_df.head(3)

structure_name  left_cell_count  \
0                        Olfactory tubercle           6771.0   
1                             Piriform area           5348.0   
2  Retrosplenial area, dorsal part, layer 1           2026.0   

   right_cell_count  total_cells  left_volume_mm3  right_volume_mm3  \
0            5166.0      11937.0         2.488875           2.45225   
1            5904.0      11252.0         7.430750           7.54175   
2            1420.0       3446.0         0.536000           0.55350   

   total_volume_mm3  left_cells_per_mm3  right_cells_per_mm3  
0          4.941125         2720.506253          2106.636762  
1         14.972500          719.712008           782.842179  
2          1.089500         3779.850746          2565.492322

In [55]:
tdTomato_df.head(3)

Unnamed: 0                            structure_name  left_cell_count  \
0           0                        Olfactory tubercle           6771.0   
1           1                             Piriform area           5348.0   
2           2  Retrosplenial area, dorsal part, layer 1           2026.0   

   right_cell_count  total_cells  left_volume_mm3  right_volume_mm3  \
0            5166.0        50706         2.488875           2.45225   
1            5904.0         1188         7.430750           7.54175   
2            1420.0        16233         0.536000           0.55350   

   total_volume_mm3  left_cells_per_mm3  right_cells_per_mm3  
0          4.941125         2720.506253          2106.636762  
1         14.972500          719.712008           782.842179  
2          1.089500         3779.850746          2565.492322

In [56]:
labled_cells_df

Unnamed: 0  gfp cell count  \
0                                   Olfactory tubercle         11937.0   
1                                        Piriform area         11252.0   
2             Retrosplenial area, dorsal part, layer 1          3446.0   
3           Retrosplenial area, dorsal part, layer 2/3          2856.0   
4    Retrosplenial area, lateral agranular part, la...          2342.0   
..                                                 ...             ...   
663              Interpeduncular nucleus, intermediate             0.0   
664               Interpeduncular nucleus, dorsomedial             0.0   
665              Interpeduncular nucleus, dorsolateral             0.0   
666             Interpeduncular nucleus, rostrolateral             0.0   
667                Supraoculomotor periaqueductal gray             0.0   

     tdTomato cell count  percent labled gfp/tdTomato  \
0                  11342                   105.245988   
1                  12930                    87.022428   
2                  12089                    28.505253   
3                  10521                    27.145709   
4                  10185                    22.994600   
..                   ...                          ...   
663                11785                     0.000000   
664                 9143                     0.000000   
665                12426                     0.000000   
666                13082                     0.000000   
667                13819                     0.000000   

     percent_cell_count_left  percent_cell_count_right  \
0                        NaN                       NaN   
1                        NaN                       NaN   
2                        NaN                       NaN   
3                        NaN                       NaN   
4                        NaN                       NaN   
..                       ...                       ...   
663                      NaN                       NaN   
664                      NaN                       NaN   
665                      NaN                       NaN   
666                      NaN                       NaN   
667                      NaN                       NaN   

     percent_volume_per_mm3_left  percent_percent_volume_per_mm3_right  \
0                            NaN                                   NaN   
1                            NaN                                   NaN   
2                            NaN                                   NaN   
3                            NaN                                   NaN   
4                            NaN                                   NaN   
..                           ...                                   ...   
663                          NaN                                   NaN   
664                          NaN                                   NaN   
665                          NaN                                   NaN   
666                          NaN                                   NaN   
667                          NaN                                   NaN   

     percent_cells_per_mm3_right  percent_cells_per_mm3_left  
0                            NaN                         NaN  
1                            NaN                         NaN  
2                            NaN                         NaN  
3                            NaN                         NaN  
4                            NaN                         NaN  
..                           ...                         ...  
663                          NaN                         NaN  
664                          NaN                         NaN  
665                          NaN                         NaN  
666                          NaN                         NaN  
667                          NaN                         NaN  

[668 rows x 10 columns]

In [57]:
summary_df

Unnamed: 0  total whole-brain cell count  total brain regions  \
0        GFP                       68313.0                  308   
1   tdTomato                     8021603.0                  668   

                                  brain regions list  
0  ['Olfactory tubercle', 'Piriform area', 'Retro...  
1  ['Olfactory tubercle', 'Piriform area', 'Retro...

# Cellfinders inital outputs

In [48]:
gfp_df 

structure_name  left_cell_count  \
0                                   Olfactory tubercle           6771.0   
1                                        Piriform area           5348.0   
2             Retrosplenial area, dorsal part, layer 1           2026.0   
3           Retrosplenial area, dorsal part, layer 2/3           1575.0   
4    Retrosplenial area, lateral agranular part, la...           1413.0   
..                                                 ...              ...   
663              Interpeduncular nucleus, intermediate              0.0   
664               Interpeduncular nucleus, dorsomedial              0.0   
665              Interpeduncular nucleus, dorsolateral              0.0   
666             Interpeduncular nucleus, rostrolateral              0.0   
667                Supraoculomotor periaqueductal gray              0.0   

     right_cell_count  total_cells  left_volume_mm3  right_volume_mm3  \
0              5166.0      11937.0         2.488875          2.452250   
1              5904.0      11252.0         7.430750          7.541750   
2              1420.0       3446.0         0.536000          0.553500   
3              1281.0       2856.0         0.649250          0.642625   
4               929.0       2342.0         0.333000          0.330250   
..                ...          ...              ...               ...   
663               0.0          0.0         0.025500          0.022750   
664               0.0          0.0         0.013125          0.011875   
665               0.0          0.0         0.025250          0.025625   
666               0.0          0.0         0.011250          0.012000   
667               0.0          0.0         0.028625          0.026125   

     total_volume_mm3  left_cells_per_mm3  right_cells_per_mm3  
0            4.941125         2720.506253          2106.636762  
1           14.972500          719.712008           782.842179  
2            1.089500         3779.850746          2565.492322  
3            1.291875         2425.876011          1993.386501  
4            0.663250         4243.243243          2813.020439  
..                ...                 ...                  ...  
663          0.048250            0.000000             0.000000  
664          0.025000            0.000000             0.000000  
665          0.050875            0.000000             0.000000  
666          0.023250            0.000000             0.000000  
667          0.054750            0.000000             0.000000  

[668 rows x 9 columns]

In [49]:
tdTomato_df

Unnamed: 0                                     structure_name  \
0             0                                 Olfactory tubercle   
1             1                                      Piriform area   
2             2           Retrosplenial area, dorsal part, layer 1   
3             3         Retrosplenial area, dorsal part, layer 2/3   
4             4  Retrosplenial area, lateral agranular part, la...   
..          ...                                                ...   
663         663              Interpeduncular nucleus, intermediate   
664         664               Interpeduncular nucleus, dorsomedial   
665         665              Interpeduncular nucleus, dorsolateral   
666         666             Interpeduncular nucleus, rostrolateral   
667         667                Supraoculomotor periaqueductal gray   

     left_cell_count  right_cell_count  total_cells  left_volume_mm3  \
0             6771.0            5166.0        50706         2.488875   
1             5348.0            5904.0         1188         7.430750   
2             2026.0            1420.0        16233         0.536000   
3             1575.0            1281.0         9762         0.649250   
4             1413.0             929.0        84720         0.333000   
..               ...               ...          ...              ...   
663              0.0               0.0        25648         0.025500   
664              0.0               0.0        37459         0.013125   
665              0.0               0.0        56380         0.025250   
666              0.0               0.0        88194         0.011250   
667              0.0               0.0        75532         0.028625   

     right_volume_mm3  total_volume_mm3  left_cells_per_mm3  \
0            2.452250          4.941125         2720.506253   
1            7.541750         14.972500          719.712008   
2            0.553500          1.089500         3779.850746   
3            0.642625          1.291875         2425.876011   
4            0.330250          0.663250         4243.243243   
..                ...               ...                 ...   
663          0.022750          0.048250            0.000000   
664          0.011875          0.025000            0.000000   
665          0.025625          0.050875            0.000000   
666          0.012000          0.023250            0.000000   
667          0.026125          0.054750            0.000000   

     right_cells_per_mm3  
0            2106.636762  
1             782.842179  
2            2565.492322  
3            1993.386501  
4            2813.020439  
..                   ...  
663             0.000000  
664             0.000000  
665             0.000000  
666             0.000000  
667             0.000000  

[668 rows x 10 columns]

In [50]:
summary_df_0

structure_name  left_cell_count  \
0                                   Olfactory tubercle           6771.0   
1                                        Piriform area           5348.0   
2             Retrosplenial area, dorsal part, layer 1           2026.0   
3           Retrosplenial area, dorsal part, layer 2/3           1575.0   
4    Retrosplenial area, lateral agranular part, la...           1413.0   
..                                                 ...              ...   
663              Interpeduncular nucleus, intermediate              0.0   
664               Interpeduncular nucleus, dorsomedial              0.0   
665              Interpeduncular nucleus, dorsolateral              0.0   
666             Interpeduncular nucleus, rostrolateral              0.0   
667                Supraoculomotor periaqueductal gray              0.0   

     right_cell_count  total_cells  left_volume_mm3  right_volume_mm3  \
0              5166.0      11937.0         2.488875          2.452250   
1              5904.0      11252.0         7.430750          7.541750   
2              1420.0       3446.0         0.536000          0.553500   
3              1281.0       2856.0         0.649250          0.642625   
4               929.0       2342.0         0.333000          0.330250   
..                ...          ...              ...               ...   
663               0.0          0.0         0.025500          0.022750   
664               0.0          0.0         0.013125          0.011875   
665               0.0          0.0         0.025250          0.025625   
666               0.0          0.0         0.011250          0.012000   
667               0.0          0.0         0.028625          0.026125   

     total_volume_mm3  left_cells_per_mm3  right_cells_per_mm3  
0            4.941125         2720.506253          2106.636762  
1           14.972500          719.712008           782.842179  
2            1.089500         3779.850746          2565.492322  
3            1.291875         2425.876011          1993.386501  
4            0.663250         4243.243243          2813.020439  
..                ...                 ...                  ...  
663          0.048250            0.000000             0.000000  
664          0.025000            0.000000             0.000000  
665          0.050875            0.000000             0.000000  
666          0.023250            0.000000             0.000000  
667          0.054750            0.000000             0.000000  

[668 rows x 9 columns]